# Generated by Django 5.1.15 on 2026-03-25 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('storage_provider', models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], db_index=True, default='local', max_length=20)),
                ('object_key', models.CharField(blank=True, db_index=True, max_length=500)),
                ('bucket_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('is_public', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to='mediafiles.uploadedmedia')),
            ],
            options={
                'db_table': 'message_attachments',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadedmedia',
            index=models.Index(fields=['owner', 'status'], name='uploaded_me_owner_i_ef61b6_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedmedia',
            index=models.Index(fields=['object_key'], name='uploaded_me_object__86ba47_idx'),
        ),
        migrations.AddConstraint(
            model_name='messageattachment',
            constraint=models.UniqueConstraint(fields=('message', 'media'), name='uniq_message_media_attachment'),
        ),
    ]
