# Generated by Django 5.1.15 on 2026-03-25 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmedia',
            name='media_kind',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], db_index=True, default='file', max_length=20),
        ),
        migrations.AddIndex(
            model_name='uploadedmedia',
            index=models.Index(fields=['owner', 'media_kind'], name='uploaded_me_owner_i_3a0f44_idx'),
        ),
    ]
