# Generated by Django 5.1.15 on 2026-03-25 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'knowledge_base_categories',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='knowledge-base/covers/')),
                ('content', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='knowledge_base.knowledgebasecategory')),
            ],
            options={
                'db_table': 'knowledge_base_articles',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('section_type', models.CharField(choices=[('text', 'Text'), ('bullets', 'Bullets'), ('steps', 'Steps'), ('faq', 'FAQ'), ('callout', 'Callout')], db_index=True, default='text', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='knowledge_base.knowledgebasearticle')),
            ],
            options={
                'db_table': 'knowledge_base_sections',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebasearticle',
            index=models.Index(fields=['slug'], name='knowledge_b_slug_c6f597_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasearticle',
            index=models.Index(fields=['category', 'is_active'], name='knowledge_b_categor_c64b50_idx'),
        ),
    ]
