# Generated by Django 5.1.15 on 2026-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_onetimecode_user_registration_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
