map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80;
    server_name aky-cheshmesi.ru www.aky-cheshmesi.ru;

    client_max_body_size 30M;

    location = /privacy {
        root /usr/share/nginx/html;
        try_files /privacy.html =404;
    }

    location = / {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location /static/ {
        alias /var/www/static/;
        access_log off;
        expires 7d;
    }

    location /media/ {
        alias /var/www/media/;
        access_log off;
        expires 7d;
    }

    location /ws {
        proxy_pass http://go-realtime:8081;
        proxy_http_version 1.1;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://django:8000;
        proxy_http_version 1.1;
        proxy_read_timeout 120;
        proxy_send_timeout 120;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://django:8000;
        proxy_http_version 1.1;
        proxy_read_timeout 120;
        proxy_send_timeout 120;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://django:8000;
        proxy_http_version 1.1;
        proxy_read_timeout 120;
        proxy_send_timeout 120;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
